Repository DeveloperAcademy-POSTECH/MC3-Team15-RockStars, pull requests merged in 2023-07, with the labels that each got.

#9 [FEAT] 프로젝트 폴더 구조 수정
  DrivePal.xcodeproj/project.pbxproj
  DrivePal/DrivePal.xcodeproj/project.pbxproj
  DrivePal/DrivePal/DrivePal.entitlements
  DrivePal/DrivePal/UserDefaults+Extensions.swift
  DrivePal/DrivePalWidgetExtensionExtension.entitlements
Labels: 🚧 refactoring

#11 [chore][#4] Team Provisioning Profile 설정
  DrivePal.xcodeproj/project.pbxproj
  DrivePal.xcodeproj/xcshareddata/xcschemes/DrivePalWidgetExtensionExtension.xcscheme
Labels: 🚧 refactoring

#12 [feat][#7] compact dynamic island view 구현
  DrivePal.xcodeproj/project.pbxproj
  DrivePal/DriveModel.swift
  DrivePal/DrivePalApp.swift
  DrivePal/DrivePalWidgetExtensionAttributes.swift
  DrivePal/View/DrivingPalView.swift
  DrivePalWidgetExtension/DrivePalWidgetExtensionLiveActivity.swift
Labels: ✨ feature

#13 [feat][#6] 개발한 단위 기능의 이름
  DrivePal.xcodeproj/project.pbxproj
  DrivePal/DriveModel.swift
  DrivePal/DrivePal.entitlements
  DrivePal/DrivePal.xcodeproj/xcshareddata/xcschemes/DrivePal.xcscheme
  DrivePal/DrivePal.xcodeproj/xcshareddata/xcschemes/DrivePalWidgetExtensionExtension.xcscheme
  DrivePal/DrivePal/DrivePalApp.swift
  DrivePal/DrivePal/UserDefaults+Extensions.swift
  DrivePal/DrivePalApp.swift
  DrivePal/UserDefaults+Extensions.swift
  DrivePal/View/DrivingPalView.swift
  DrivePal/View/Scene/BackgroundScene.swift
  DrivePal/View/Shake.swift
  DrivePalWidgetExtension/DrivePalWidgetExtension.swift
  DrivePalWidgetExtension/DrivePalWidgetExtensionLiveActivity.swift
  DrivePalWidgetExtensionExtension.entitlements
Labels: ✨ feature

#16 [docs][#15] README.md 초안 작성
  README.md
Labels: 📑 documentation

#20 [feat][#19] 속도 구하기
  DrivePal.xcodeproj/project.pbxproj
  DrivePal/Info.plist
  DrivePal/LocationsHandler.swift
  DrivePal/View/DrivingPalView.swift
  DrivePalWidgetExtension/DrivePalWidgetExtension.entitlements
Labels: ✨ feature

#28 [feat][#17] automotive 상태를 감지하기
  DrivePal.xcodeproj/project.pbxproj
  DrivePal/ContentView.swift
  DrivePal/DrivePalApp.swift
  DrivePal/Info.plist
  DrivePal/Utils/Extensions/Bundle+Extension.swift
  DrivePal/Utils/Extensions/UserDefaults+Extensions.swift
  DrivePal/View/DrivingPalView.swift
Labels: ✨ feature

#29 [refactor][#25] view and model 리펙터링(DrivePalView) 위주
  DrivePal.xcodeproj/project.pbxproj
  DrivePal/DrivePalApp.swift
  DrivePal/LiveActivityModel.swift
  DrivePal/LocationsHandler.swift
  DrivePal/UIScreen+Extensions.swift
  DrivePal/View/DrivingPalView.swift
  DrivePal/View/Shake.swift
  DrivePal/View/VelocityView.swift
Labels: 🚧 refactoring

#39 [feat][#26] 화면 변환 작업
  DrivePal/Assets.xcassets/airPlane.imageset/Contents.json
  DrivePal/Assets.xcassets/airPlane.imageset/airPlane.png
  DrivePal/Assets.xcassets/airPlaneShadow.imageset/Contents.json
  DrivePal/Assets.xcassets/airPlaneShadow.imageset/airPlaneShadow.png
  DrivePal/Assets.xcassets/finishAirport.imageset/Contents.json
  DrivePal/Assets.xcassets/finishAirport.imageset/finishAirport.jpg
  DrivePal/Assets.xcassets/startRunway.imageset/Contents.json
  DrivePal/Assets.xcassets/startRunway.imageset/startRunway.jpg
  DrivePal/DrivePalApp.swift
  DrivePal/Model/LiveActivity/LiveActivityModel.swift
  DrivePal/View/DrivingPalView.swift
  DrivePal/View/Scene/BackgroundScene.swift
Labels: ✨ feature

#40 [feat][#30] 주행 완료 후 보이는 결과뷰를 만들었어요
  DrivePal.xcodeproj/project.pbxproj
  DrivePal/Assets.xcassets/BackgroundImage/Contents.json
  DrivePal/Assets.xcassets/BackgroundImage/blueSky.imageset/BlueSky.jpg
  DrivePal/Assets.xcassets/BackgroundImage/blueSky.imageset/Contents.json
  DrivePal/Assets.xcassets/BackgroundImage/redSky.imageset/Contents.json
  DrivePal/Assets.xcassets/BackgroundImage/redSky.imageset/RedSky.jpg
  DrivePal/Assets.xcassets/DrivingCompleted/Contents.json
  DrivePal/Assets.xcassets/DrivingCompleted/goodDriver.imageset/Contents.json
  DrivePal/Assets.xcassets/DrivingCompleted/goodDriver.imageset/goodDriver.png
  DrivePal/Assets.xcassets/WhileDriving/Contents.json
  DrivePal/Assets.xcassets/WhileDriving/planeWithShadow.imageset/Contents.json
  DrivePal/Assets.xcassets/WhileDriving/planeWithShadow.imageset/planeWithShadow.png
  DrivePal/Assets.xcassets/warning1.imageset/Contents.json
  DrivePal/Assets.xcassets/warning1.imageset/warning1.png
  DrivePal/Assets.xcassets/warning1.imageset/warning1@2x.png
  DrivePal/Assets.xcassets/warning1.imageset/warning1@3x.png
  DrivePal/Assets.xcassets/warning2.imageset/Contents.json
  DrivePal/Assets.xcassets/warning2.imageset/warning2.png
  DrivePal/Assets.xcassets/warning2.imageset/warning2@2x.png
  DrivePal/Assets.xcassets/warning2.imageset/warning2@3x.png
  DrivePal/Assets.xcassets/warning3.imageset/Contents.json
  DrivePal/Assets.xcassets/warning3.imageset/warning3.png
  DrivePal/Assets.xcassets/warning3.imageset/warning3@2x.png
  DrivePal/Assets.xcassets/warning3.imageset/warning3@3x.png
  DrivePal/Assets.xcassets/warning4.imageset/Contents.json
  DrivePal/Assets.xcassets/warning4.imageset/warning4.png
  DrivePal/Assets.xcassets/warning4.imageset/warning4@2x.png
  DrivePal/Assets.xcassets/warning4.imageset/warning4@3x.png
  DrivePal/Assets.xcassets/warning5.imageset/Contents.json
  DrivePal/Assets.xcassets/warning5.imageset/warning5.png
  DrivePal/Assets.xcassets/warning5.imageset/warning5@2x.png
  DrivePal/Assets.xcassets/warning5.imageset/warning5@3x.png
  DrivePal/Assets.xcassets/warning6.imageset/Contents.json
  DrivePal/Assets.xcassets/warning6.imageset/warning6.png
  DrivePal/Assets.xcassets/warning6.imageset/warning6@2x.png
  DrivePal/Assets.xcassets/warning6.imageset/warning6@3x.png
  DrivePal/DrivePalApp.swift
  DrivePal/Model/LiveActivity/DriveSimulator.swift
  DrivePal/Model/LiveActivity/LiveActivityModel.swift
  DrivePal/Utils/Extensions/Color+Extension.swift
  DrivePal/Utils/Extensions/Text+Extension.swift
  DrivePal/Utils/Extensions/UserDefaults+Extension.swift
  DrivePal/Utils/NavigationUtil.swift
  DrivePal/View/ChartView.swift
  DrivePal/View/DrivingPalView.swift
  DrivePal/View/ResultAnalysisView.swift
Labels: ✨ feature

#42 [feat][#26] 이륙 착륙 에니메이션 추가
  DrivePal/Assets.xcassets/exit.imageset/Contents.json
  DrivePal/Assets.xcassets/exit.imageset/exit.png
  DrivePal/View/DrivingPalView.swift
Labels: ✨ feature

#44 [feat][#27] 다이나믹 아일랜드 Expanded Appearance 추가
  DrivePal.xcodeproj/project.pbxproj
  DrivePal/Model/LiveActivity/DriveAttributes.swift
  DrivePal/Model/LiveActivity/DriveSimulator.swift
  DrivePal/Model/LiveActivity/LiveActivityModel.swift
  DrivePal/View/DrivingPalView.swift
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LocationPin/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LocationPin/locationPinBlue.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LocationPin/locationPinBlue.imageset/locationPinBlue.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LocationPin/locationPinPink.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LocationPin/locationPinPink.imageset/locationPinPink.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LocationPin/locationPinRed.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LocationPin/locationPinRed.imageset/locationPinRed.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LocationPin/locationPinYellow.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LocationPin/locationPinYellow.imageset/locationPinYellow.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignBackground/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignBackground/warnSignBackground.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignBackground/warnSignBackground.imageset/warnSignBackground.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignMeteor/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignMeteor/warnSignMeteor1.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignMeteor/warnSignMeteor1.imageset/warnSignMeteor1.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignMeteor/warnSignMeteor2.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignMeteor/warnSignMeteor2.imageset/warnSignMeteor2.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignMeteor/warnSignMeteor3.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignMeteor/warnSignMeteor3.imageset/warnSignMeteor3.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignMeteor/warnSignMeteor4.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignMeteor/warnSignMeteor4.imageset/warnSignMeteor4.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignMeteor/warnSignMeteor5.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignMeteor/warnSignMeteor5.imageset/warnSignMeteor5.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignMeteor/warnSignMeteor6.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignMeteor/warnSignMeteor6.imageset/warnSignMeteor6.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignThunder/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignThunder/warnSignThunder1.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignThunder/warnSignThunder1.imageset/warnSignThunder1.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignThunder/warnSignThunder2.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignThunder/warnSignThunder2.imageset/warnSignThunder2.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignThunder/warnSignThunder3.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignThunder/warnSignThunder3.imageset/warnSignThunder3.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignThunder/warnSignThunder4.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignThunder/warnSignThunder4.imageset/warnSignThunder4.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignThunder/warnSignThunder5.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignThunder/warnSignThunder5.imageset/warnSignThunder5.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignThunder/warnSignThunder6.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/WarnSignThunder/warnSignThunder6.imageset/warnSignThunder6.png
  DrivePalWidgetExtension/DrivePalWidgetExtensionLiveActivity.swift
  DrivePalWidgetExtension/View/AfterFourWarningsView.swift
  DrivePalWidgetExtension/View/CircularProgressView.swift
  DrivePalWidgetExtension/View/LinearProgressView.swift
  DrivePalWidgetExtension/View/NormalDrivingView.swift
  DrivePalWidgetExtension/View/SuddenAccelerationView.swift
  DrivePalWidgetExtension/View/SuddenStopView.swift
Labels: ✨ feature

#54 [feat][#49] Lock Screen View 개발
  DrivePal/Model/LiveActivity/DriveAttributes.swift
  DrivePal/Model/LiveActivity/DriveSimulator.swift
  DrivePal/Model/LiveActivity/LiveActivityModel.swift
  DrivePal/View/DrivingPalView.swift
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LocationPin/locationPinBlack.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LocationPin/locationPinBlack.imageset/locationPinBlack.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LocationPin/locationPinGray.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LocationPin/locationPinGray.imageset/locationPinGray.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LockScreen/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LockScreen/lockScreen1.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LockScreen/lockScreen1.imageset/lockScreen1.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LockScreen/lockScreen2.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LockScreen/lockScreen2.imageset/lockScreen2.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LockScreen/lockScreen3.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LockScreen/lockScreen3.imageset/lockScreen3.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LockScreen/lockScreen4.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LockScreen/lockScreen4.imageset/lockScreen4.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LockScreen/lockScreen5.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LockScreen/lockScreen5.imageset/lockScreen5.png
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LockScreen/lockScreen6.imageset/Contents.json
  DrivePalWidgetExtension/Assets.xcassets/CompactDynamicIsland/LockScreen/lockScreen6.imageset/lockScreen6.png
  DrivePalWidgetExtension/DrivePalWidgetExtensionLiveActivity.swift
Labels: ✨ feature

#52 [fix][#50] 둥실 둥실 애니메이션 수정
  DrivePal/View/DrivingPalView.swift
Labels: 🐛 bug

#58 [refactor][#53] DrivePalView 해체쇼
  DrivePal.xcodeproj/project.pbxproj
  DrivePal/DrivePalApp.swift
  DrivePal/Model/LiveActivity/DriveSimulator.swift
  DrivePal/Model/Location/LocationsHandler.swift
  DrivePal/Model/Motion/MotionHandler.swift
  DrivePal/View/ConvertibleBackgroundView.swift
  DrivePal/View/DrivingPalView.swift
  DrivePal/View/DrivingStartView.swift
  DrivePal/View/ExitButton.swift
  DrivePal/View/PlaneView.swift
  DrivePal/View/Scene/BackgroundScene.swift
  DrivePal/View/VelocityView.swift
Labels: 🚧 refactoring

#65 [fix][#61] 가속도 기반이 아닌 속도 기반으로 급감속과 급가속을 측정
  DrivePal.xcodeproj/project.pbxproj
  DrivePal/Sources/Model/Location/LocationsHandler.swift
  DrivePal/Sources/View/DrivingPalView.swift
  DrivePal/Sources/View/PlaneView.swift
  DrivePal/Sources/View/VelocityView.swift
Labels: 🚧 refactoring, ✨ feature

#75 [fix][#74] 엘리베이션 기능 수정 및 애니메이션 매끄럽게 하는 작업
  DrivePal/Sources/View/DrivingPalView.swift
  DrivePal/Sources/View/PlaneView.swift
Labels: 🐛 bug
