Repository DeveloperAcademy-POSTECH/MC3-Team15-RockStars, pull requests merged in 2023-08, with the labels that each got.

#82 [feat][#81] Pop Out되는 애니메이션 뷰 적용
  DrivePal.xcodeproj/project.pbxproj
  DrivePal/Resources/Localization/en.lproj/Localizable.strings
  DrivePal/Resources/Localization/ko.lproj/Localizable.strings
  DrivePal/Sources/Utils/I18N.swift
  DrivePal/Sources/View/DrivingPalView.swift
  DrivePal/Sources/View/DynamicInformView.swift
Labels: ✨ feature

#88 [feat][#85] 스킴 분리 + Location Handler 약간 수정
  DrivePal.xcodeproj/project.pbxproj
  DrivePal.xcodeproj/xcshareddata/xcschemes/DrivePal.xcscheme
  DrivePal/Resources/Localization/en.lproj/Localizable.strings
  DrivePal/Resources/Localization/ko.lproj/Localizable.strings
  DrivePal/Sources/DrivePalApp.swift
  DrivePal/Sources/Model/Location/LocationsHandler.swift
  DrivePal/Sources/Utils/I18N.swift
  DrivePal/Sources/View/ConvertibleBackgroundView.swift
  DrivePal/Sources/View/DrivingPalView.swift
  DrivePal/Sources/View/DynamicInformView.swift
  DrivePal/Sources/View/OnboardingView.swift
  DrivePal/Sources/View/PlaneView.swift
  DrivePal/Sources/View/VelocityView.swift
Labels: ✨ feature

#86 [feat][#84] 다이나믹 아일랜드 디자인 추가 및 수정
  DrivePal/Sources/Model/LiveActivity/DriveSimulator.swift
  DrivePal/Sources/Utils/Extensions/Color+Extension.swift
  DrivePalWidgetExtension/View/ExpandedView.swift
Labels: ✨ feature

#90 [feat][#62] 위치 권한 획득 후에 즉시 VelocityView 업데이트 되도록 설정
  DrivePal/Sources/Model/Location/LocationsHandler.swift
  DrivePal/Sources/View/DrivingPalView.swift
Labels: 🚨 hotfix

#92 [fix][#91] 비정상이 되면 3초 동안 업데이트를 막게 수정
  DrivePal/Sources/Model/Location/LocationsHandler.swift
  DrivePal/Sources/Model/Motion/MotionHandler.swift
Labels: 🚨 hotfix

#94 [hotfix] location 업데이트를 아예 중단하면서 발생하는 버그 해결
  DrivePal.xcodeproj/project.pbxproj
  DrivePal.xcodeproj/xcshareddata/xcschemes/DrivePal.xcscheme
  DrivePal/Sources/Model/Location/LocationsHandler.swift
Labels: 🚨 hotfix

#102 [feat][#99] 위치 데이터를 다이나믹아일랜드에 업데이트
  DrivePal/Resources/Localization/en.lproj/Localizable.strings
  DrivePal/Resources/Localization/ko.lproj/Localizable.strings
  DrivePal/Sources/Model/LiveActivity/DriveAttributes.swift
  DrivePal/Sources/Model/LiveActivity/DriveSimulator.swift
  DrivePal/Sources/Model/LiveActivity/LiveActivityModel.swift
  DrivePal/Sources/Model/Location/LocationsHandler.swift
  DrivePal/Sources/Utils/I18N.swift
  DrivePal/Sources/View/DrivingPalView.swift
  DrivePalWidgetExtension/DrivePalWidgetExtensionLiveActivity.swift
  DrivePalWidgetExtension/View/ExpandedView.swift
Labels: ✨ feature

#103 [feat][#95] 부주의가 감지되지 않은 경우 차트뷰
  DrivePal/Resources/Assets.xcassets/BackgroundImage/Contents.json
  DrivePal/Resources/Assets.xcassets/BackgroundImage/resultBackgroundImagePerfect.imageset/Contents.json
  DrivePal/Resources/Assets.xcassets/BackgroundImage/resultBackgroundImagePerfect.imageset/resultBackgroundImagePerfect.png
  DrivePal/Resources/Assets.xcassets/DrivingCompleted/resultPalImagePerfect.imageset/Contents.json
  DrivePal/Resources/Assets.xcassets/DrivingCompleted/resultPalImagePerfect.imageset/resultPalImagePerfect.png
  DrivePal/Resources/Assets.xcassets/DrivingCompleted/resultPalImagePerfect.imageset/resultPalImagePerfect@2x.png
  DrivePal/Resources/Assets.xcassets/DrivingCompleted/resultPalImagePerfect.imageset/resultPalImagePerfect@3x.png
  DrivePal/Sources/Utils/Extensions/String+Extension.swift
  DrivePal/Sources/View/Result/ResultAnalysisView.swift
  DrivePal/Sources/View/Result/ResultDataBoxView.swift
  DrivePal/Sources/View/Result/ResultTabView.swift
Labels: ✨ feature

#105 [fix][#104] changing app name and turning off localization
  DrivePal.xcodeproj/project.pbxproj
Labels: 📑 documentation

#110 [chore][#108] fastlane 적용
  .gitignore
  DrivePal.xcodeproj/project.pbxproj
  DrivePal/Resources/Info.plist
  Gemfile
  Gemfile.lock
  fastlane/Appfile
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/README.md
  fastlane/metadata/app_store_rating_config.json
  fastlane/metadata/copyright.txt
  fastlane/metadata/ko/apple_tv_privacy_policy.txt
  fastlane/metadata/ko/description.txt
  fastlane/metadata/ko/keywords.txt
  fastlane/metadata/ko/marketing_url.txt
  fastlane/metadata/ko/name.txt
  fastlane/metadata/ko/privacy_url.txt
  fastlane/metadata/ko/promotional_text.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/ko/subtitle.txt
  fastlane/metadata/ko/support_url.txt
  fastlane/metadata/primary_category.txt
  fastlane/metadata/primary_first_sub_category.txt
  fastlane/metadata/primary_second_sub_category.txt
  fastlane/metadata/review_information/demo_password.txt
  fastlane/metadata/review_information/demo_user.txt
  fastlane/metadata/review_information/email_address.txt
  fastlane/metadata/review_information/first_name.txt
  fastlane/metadata/review_information/last_name.txt
  fastlane/metadata/review_information/notes.txt
  fastlane/metadata/review_information/phone_number.txt
  fastlane/metadata/secondary_category.txt
  fastlane/metadata/secondary_first_sub_category.txt
  fastlane/metadata/secondary_second_sub_category.txt
  fastlane/screenshots/README.txt
Labels: ✨ feature

#111 [feature] 사용하는 권한 뷰 설정 및 권한 요청 흐름 변화
  DrivePal.xcodeproj/project.pbxproj
  DrivePal/Resources/Localization/ko.lproj/Localizable.strings
  DrivePal/Sources/DrivePalApp.swift
  DrivePal/Sources/Model/Location/LocationsHandler.swift
  DrivePal/Sources/Utils/Extensions/String+Extension.swift
  DrivePal/Sources/Utils/I18N.swift
  DrivePal/Sources/View/AuthorizationRequestView.swift
  DrivePal/Sources/View/ConvertibleBackgroundView.swift
  DrivePal/Sources/View/DrivingPalView.swift
  DrivePal/Sources/View/DrivingStartView.swift
Labels: ✨ feature
